version: '3.8'

services:
  neo4j:
    image: neo4j:5.10
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7687:7687"  # Bolt protocol port for Neo4j
      - "7474:7474"  # HTTP web interface
